\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Assignment 2},
            pdfauthor={Evan Walker},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Assignment 2}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Evan Walker}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{September 24, 2018}


\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#setwd("~/Desktop/Mathemagic/Fall2019/CS614_Interactive_Data_Analysis/Homework_614/HW2")}
\KeywordTok{load}\NormalTok{(}\StringTok{'accel.RData'}\NormalTok{)}
\NormalTok{d =}\StringTok{ }\NormalTok{df}
\KeywordTok{summary}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  participant_id      goal_minutes        wear           bout.min     
##  Length:376         Min.   : 3.00   Min.   : 156.7   Min.   :  0.10  
##  Class :character   1st Qu.:24.40   1st Qu.: 621.4   1st Qu.: 12.74  
##  Mode  :character   Median :30.00   Median : 765.0   Median : 22.70  
##                     Mean   :28.21   Mean   : 791.3   Mean   : 24.94  
##                     3rd Qu.:30.00   3rd Qu.: 922.2   3rd Qu.: 31.21  
##                     Max.   :58.41   Max.   :1413.2   Max.   :108.71  
##       Age            Sex           BMI           income         
##  Min.   :19.00   Female:244   Min.   :19.90   Length:376        
##  1st Qu.:38.00   Male  :132   1st Qu.:28.27   Class :character  
##  Median :46.00                Median :31.65   Mode  :character  
##  Mean   :45.38                Mean   :33.18                     
##  3rd Qu.:53.00                3rd Qu.:36.90                     
##  Max.   :60.00                Max.   :57.80                     
##      walk          
##  Length:376        
##  Class :character  
##  Mode  :character  
##                    
##                    
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    376 obs. of  9 variables:
##  $ participant_id: chr  "5011" "5011" "5014" "5015" ...
##  $ goal_minutes  : num  3.56 24.09 30 13.43 30 ...
##  $ wear          : num  596 777 780 721 513 ...
##  $ bout.min      : num  1.57 30.51 25.32 13.31 18.73 ...
##  $ Age           : int  35 32 27 41 43 48 37 36 56 32 ...
##  $ Sex           : Factor w/ 2 levels "Female","Male": 1 1 1 1 1 1 1 1 1 1 ...
##  $ BMI           : num  26.3 31.9 28.2 26.9 28.8 44.8 46.1 34.1 35.2 39.5 ...
##  $ income        : chr  "high" "high" "low" "high" ...
##  $ walk          : chr  "low" "high" "high" "low" ...
\end{verbatim}

\subsection{Exercise 1.}\label{exercise-1.}

Study recruitment was based on income/walkability quadrants where the
design called for roughly equal number of people from Hi Income/Hi Walk,
Hi Income/Low Walk, Low Income/High Walk, and Low Income/Low Walk.
Determine if the recruitment goal of equal quadrants was met by creating
a new variable that combines the information in the income and
walkability variables. Create a bar plot for this new variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wlkinc=d}\OperatorTok{$}\NormalTok{walk}
\NormalTok{wlkinc[}\KeywordTok{intersect}\NormalTok{(}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{income }\OperatorTok{==}\StringTok{"high"}\NormalTok{),}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{walk }\OperatorTok{==}\StringTok{ "high"}\NormalTok{))] =}\StringTok{ "hi/hi"}
\NormalTok{wlkinc[}\KeywordTok{intersect}\NormalTok{(}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{income }\OperatorTok{==}\StringTok{"high"}\NormalTok{),}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{walk }\OperatorTok{==}\StringTok{ "low"}\NormalTok{))]  =}\StringTok{ "hi/lo"}
\NormalTok{wlkinc[}\KeywordTok{intersect}\NormalTok{(}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{income }\OperatorTok{==}\StringTok{"low"}\NormalTok{),}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{walk }\OperatorTok{==}\StringTok{ "high"}\NormalTok{))]  =}\StringTok{ "lo/hi"}
\NormalTok{wlkinc[}\KeywordTok{intersect}\NormalTok{(}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{income }\OperatorTok{==}\StringTok{"low"}\NormalTok{),}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{walk }\OperatorTok{==}\StringTok{ "low"}\NormalTok{))]   =}\StringTok{ "lo/lo"}

\NormalTok{check =}\StringTok{ }\KeywordTok{cbind}\NormalTok{(wlkinc,d}\OperatorTok{$}\NormalTok{income)}
\NormalTok{check =}\StringTok{ }\KeywordTok{cbind}\NormalTok{(check,d}\OperatorTok{$}\NormalTok{walk)}
\KeywordTok{head}\NormalTok{(check)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      wlkinc               
## [1,] "hi/lo" "high" "low" 
## [2,] "hi/hi" "high" "high"
## [3,] "lo/hi" "low"  "high"
## [4,] "hi/lo" "high" "low" 
## [5,] "hi/lo" "high" "low" 
## [6,] "lo/hi" "low"  "high"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d =}\StringTok{ }\KeywordTok{cbind}\NormalTok{(d,wlkinc)}
\KeywordTok{summary}\NormalTok{(d}\OperatorTok{$}\NormalTok{wlkinc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## hi/hi hi/lo lo/hi lo/lo 
##    94   106   111    65
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tt1 =}\StringTok{ }\KeywordTok{table}\NormalTok{(d}\OperatorTok{$}\NormalTok{wlkinc)}
\KeywordTok{barplot}\NormalTok{(tt1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-2-1.pdf}

Based off the barplot, its mostly evenly sampled. However, low income
and low walkability was slightly under sampled

\subsection{Exercise 2}\label{exercise-2}

Is the distribution of the average number of bout minutes or the average
number of wear minutes more skewed? Use histograms to support your
answer. Why do you think this may be? For the more skewed variable,
create a second histogram of the log transform of values.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(d}\OperatorTok{$}\NormalTok{bout.min)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.10   12.74   22.70   24.94   31.21  108.71
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(d}\OperatorTok{$}\NormalTok{wear)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   156.7   621.4   765.0   791.3   922.2  1413.2
\end{verbatim}

\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-4-1.pdf}
\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-4-2.pdf}

The bout.min variable is distributed as chi sqr, with most of the
variance explained on the left side of the distribution. This makes
sense since many people may do 20-30 min of moderate-to-vigorous
physical activity every day, but few people will do 40-60 min per day.

\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-5-1.pdf}

\subsection{Exercise 3}\label{exercise-3}

Use the tools we have been developing to explore the goal minutes
category. you see anything interesting? Can you come up with ways to
improve the information summarized in your histogram?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(d}\OperatorTok{$}\NormalTok{goal_minutes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    3.00   24.40   30.00   28.21   30.00   58.41
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(d}\OperatorTok{$}\NormalTok{goal_minutes)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(d}\OperatorTok{$}\NormalTok{goal_minutes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 28.21415
\end{verbatim}

This histogram shows goal\_minutes has very low variance about its mean
at 28 minutes. Most participants have a goal of 30 minutes, we can see
this when we call summary(goal\_minutes), it shows how the 1st and 3rd
quartile are closey packed around the mean signifying the low variance
of the distribution.

\subsection{Exercise 4}\label{exercise-4}

Use side-by-side box plots to determine whether the average number of
bout minutes differs by sex. Back up your findings with summary
statistics.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(d}\OperatorTok{$}\NormalTok{Sex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Factor w/ 2 levels "Female","Male": 1 1 1 1 1 1 1 1 1 1 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bout_male =}\StringTok{ }\NormalTok{d}\OperatorTok{$}\NormalTok{bout.min[}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{Sex }\OperatorTok{==}\StringTok{ "Male"}\NormalTok{)]}
\NormalTok{bout_female =}\StringTok{ }\NormalTok{d}\OperatorTok{$}\NormalTok{bout.min[}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{Sex }\OperatorTok{==}\StringTok{ "Female"}\NormalTok{)]}
\KeywordTok{length}\NormalTok{(bout_female)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 244
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(bout_male)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 132
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(bout_female,bout_male,}\DataTypeTok{names =} \KeywordTok{c}\NormalTok{(}\StringTok{"Female"}\NormalTok{,}\StringTok{"Male"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(bout_female)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.5167 11.8028 20.3944 23.8715 30.3181 91.6056
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(bout_male)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.10   14.00   24.43   26.91   33.88  108.71
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(bout_female,bout_male)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  bout_female and bout_male
## t = -1.5534, df = 247.46, p-value = 0.1216
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -6.8992716  0.8151545
## sample estimates:
## mean of x mean of y 
##  23.87149  26.91355
\end{verbatim}

Based of summary statistics, boxplots, and t-test we see that the
distributions are very similar. But we see that the distributions,
altough similar in shape, are off slightly, with males having roughly 3
minutes more activity a day. (the distribution of the males are shifted
to the right 3 minutes).

However there are 244 female subjects and 132 male subjects, hence
females hold 65\% of the data. with this off balance, I decided to
t-test the two groups and found a p-value of 0.1216. Thus concluded that
the true means were equal.

\subsection{Exercise 5}\label{exercise-5}

Eliminate the income and walk variables and the variable created in
Problem 1 from the data frame. Then, using the plot function, create a
matrix of scatter plots comparing every variable in thedata set to every
other. Identify two strong relationships and provide an explanation for
why they exist. Also, explain why several scatter plots have horizontal
or vertical lines in the center of the figure.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dpl =}\StringTok{ }\NormalTok{d[,}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1}\NormalTok{,}\OperatorTok{-}\DecValTok{8}\NormalTok{,}\OperatorTok{-}\DecValTok{9}\NormalTok{,}\OperatorTok{-}\DecValTok{10}\NormalTok{,}\OperatorTok{-}\DecValTok{11}\NormalTok{,}\OperatorTok{-}\DecValTok{12}\NormalTok{)]}
\KeywordTok{summary}\NormalTok{(dpl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   goal_minutes        wear           bout.min           Age       
##  Min.   : 3.00   Min.   : 156.7   Min.   :  0.10   Min.   :19.00  
##  1st Qu.:24.40   1st Qu.: 621.4   1st Qu.: 12.74   1st Qu.:38.00  
##  Median :30.00   Median : 765.0   Median : 22.70   Median :46.00  
##  Mean   :28.21   Mean   : 791.3   Mean   : 24.94   Mean   :45.38  
##  3rd Qu.:30.00   3rd Qu.: 922.2   3rd Qu.: 31.21   3rd Qu.:53.00  
##  Max.   :58.41   Max.   :1413.2   Max.   :108.71   Max.   :60.00  
##      Sex           BMI       
##  Female:244   Min.   :19.90  
##  Male  :132   1st Qu.:28.27  
##               Median :31.65  
##               Mean   :33.18  
##               3rd Qu.:36.90  
##               Max.   :57.80
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(dpl)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-8-1.pdf}

From the plots we see that goal\_minutes creates vertical/horizontal
lines in the plots. This relates to exercise 3, where we found that the
variance about the mean is very small, thus most points are at or around
the mean at 28min. This creates lines in the plots since its a
relatively constant value.

Other vertical/horizontal lines present in the plots are due to the
binary variable Sex.

One clear relaitonship is between bout.min and goal\_minutes. This is
clear since the higher your goal is, the more minutes of activity you do
a day, Hence the positive linear relationship. You would hope to see a
one-to-one correspondence such that the slope of the line is 1, which
would imply that everyone is doing exactly their goal minutes of
activity a day.

\subsection{Exercise 6}\label{exercise-6}

In class when examining the TAO data, we discussed why imputing with the
mean or a random value are not optimal imputation methods. Here, two
superior imputation methods are suggested. Please choose one and
implement it on the TAO data. Note that your procedure should be
implemented separately for the 1993 and 1997 data. Provide and updated
humidity versus air temp scatrer plot. Try to plot the 1993 and 1997
data together like we did in class.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d=}\KeywordTok{read.csv}\NormalTok{(}\StringTok{'tao.csv'}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(d)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        X              year         latitude        longitude     
##  Min.   :  1.0   Min.   :1993   Min.   :-5.000   Min.   :-110.0  
##  1st Qu.:184.8   1st Qu.:1993   1st Qu.:-2.000   1st Qu.:-110.0  
##  Median :368.5   Median :1995   Median :-1.000   Median :-102.5  
##  Mean   :368.5   Mean   :1995   Mean   :-1.375   Mean   :-102.5  
##  3rd Qu.:552.2   3rd Qu.:1997   3rd Qu.: 0.000   3rd Qu.: -95.0  
##  Max.   :736.0   Max.   :1997   Max.   : 0.000   Max.   : -95.0  
##                                                                  
##  sea.surface.temp    air.temp        humidity         uwind       
##  Min.   :21.60    Min.   :21.42   Min.   :71.60   Min.   :-8.100  
##  1st Qu.:23.50    1st Qu.:23.26   1st Qu.:81.30   1st Qu.:-5.100  
##  Median :26.55    Median :24.52   Median :85.20   Median :-3.900  
##  Mean   :25.86    Mean   :25.03   Mean   :84.43   Mean   :-3.716  
##  3rd Qu.:28.21    3rd Qu.:27.08   3rd Qu.:88.10   3rd Qu.:-2.600  
##  Max.   :30.17    Max.   :28.50   Max.   :94.80   Max.   : 4.300  
##  NA's   :3        NA's   :81      NA's   :93                      
##      vwind       
##  Min.   :-6.200  
##  1st Qu.: 1.500  
##  Median : 2.900  
##  Mean   : 2.636  
##  3rd Qu.: 4.100  
##  Max.   : 7.300  
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d_}\DecValTok{93}\NormalTok{=d[}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{year}\OperatorTok{==}\DecValTok{1993}\NormalTok{),]}
\NormalTok{d_}\DecValTok{97}\NormalTok{=d[}\KeywordTok{which}\NormalTok{(d}\OperatorTok{$}\NormalTok{year}\OperatorTok{==}\DecValTok{1997}\NormalTok{),]}

\KeywordTok{install.packages}\NormalTok{(}\StringTok{'norm'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Installing package into '/home/ewalk21/R/x86_64-pc-linux-gnu-library/3.4'
## (as 'lib' is unspecified)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(}\StringTok{'norm'}\NormalTok{)}
\NormalTok{prelim_}\DecValTok{93}\NormalTok{ <-}\StringTok{ }\KeywordTok{prelim.norm}\NormalTok{(}\KeywordTok{as.matrix}\NormalTok{(d_}\DecValTok{93}\NormalTok{))}
\NormalTok{prelim_}\DecValTok{97}\NormalTok{ <-}\StringTok{ }\KeywordTok{prelim.norm}\NormalTok{(}\KeywordTok{as.matrix}\NormalTok{(d_}\DecValTok{97}\NormalTok{))}
\NormalTok{thetaHat_}\DecValTok{93}\NormalTok{ <-}\StringTok{ }\KeywordTok{em.norm}\NormalTok{(prelim_}\DecValTok{93}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Iterations of EM: 
## 1...2...3...4...5...6...7...8...9...10...11...12...13...14...15...16...17...18...19...20...21...22...23...24...25...26...27...28...29...30...31...32...33...34...35...36...37...38...39...40...41...42...43...44...45...46...47...48...49...50...51...52...53...54...55...56...57...58...59...60...61...62...63...64...65...66...67...68...69...70...71...72...73...74...75...76...77...78...79...80...81...82...83...84...85...86...87...88...89...90...91...92...93...94...95...96...97...98...99...100...101...102...103...104...105...106...107...108...109...110...111...112...113...114...115...116...117...118...119...120...121...122...123...124...125...126...127...128...129...130...131...132...133...134...135...136...137...138...139...140...141...142...143...144...145...146...147...148...149...150...151...152...153...154...155...156...157...158...159...160...161...162...163...164...165...166...167...168...169...170...171...172...173...174...175...176...177...178...179...180...181...182...183...184...185...186...187...188...189...190...191...192...193...194...195...196...197...198...199...200...201...202...203...204...205...206...207...208...209...210...211...212...213...214...215...216...217...218...219...220...221...222...223...224...225...226...227...228...229...230...231...232...233...234...235...236...237...238...239...240...241...242...243...244...245...246...247...248...249...250...251...252...253...254...255...256...257...258...259...260...261...262...263...264...265...266...267...268...269...270...271...272...273...274...275...276...277...278...279...280...281...282...283...284...285...286...287...288...289...290...291...292...293...294...295...296...297...298...299...300...301...302...303...304...305...306...307...308...309...310...311...312...313...314...315...316...317...318...319...320...321...322...323...324...325...326...327...328...329...330...331...332...333...334...335...336...337...338...339...340...341...342...343...344...345...346...347...348...349...350...351...352...353...354...355...356...357...358...359...360...361...362...363...364...365...366...367...368...369...370...371...372...373...374...375...376...377...378...379...380...381...382...383...384...385...386...387...388...389...390...391...392...393...394...395...396...397...398...399...400...401...402...403...404...405...406...407...408...409...410...411...412...413...414...415...416...417...418...419...420...421...422...423...424...425...426...427...428...429...430...431...432...433...434...435...436...437...438...439...440...441...442...443...444...445...446...447...448...449...450...451...452...453...454...455...456...457...458...459...460...461...462...463...464...465...466...467...468...469...470...471...472...473...474...475...476...477...478...479...480...481...482...483...484...485...486...487...488...489...490...491...492...493...494...495...496...497...498...499...500...501...502...503...504...505...506...507...508...509...510...511...512...513...514...515...516...517...518...519...520...521...522...523...524...525...526...527...528...529...530...531...532...533...534...535...536...537...538...539...540...541...542...543...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{thetaHat_}\DecValTok{97}\NormalTok{ <-}\StringTok{ }\KeywordTok{em.norm}\NormalTok{(prelim_}\DecValTok{97}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Iterations of EM: 
## 1...2...3...4...5...6...7...8...9...10...11...12...13...14...15...16...17...18...19...20...21...22...23...24...25...26...27...28...29...30...31...32...33...34...35...36...37...38...39...40...41...42...43...44...45...46...47...48...49...50...51...52...53...54...55...56...57...58...59...60...61...62...63...64...65...66...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rngseed}\NormalTok{(}\DecValTok{1234}\NormalTok{)}
\NormalTok{d_}\DecValTok{93}\NormalTok{[}\KeywordTok{is.na}\NormalTok{(d_}\DecValTok{93}\NormalTok{)]<-}\KeywordTok{imp.norm}\NormalTok{(prelim_}\DecValTok{93}\NormalTok{, thetaHat_}\DecValTok{93}\NormalTok{, d_}\DecValTok{93}\NormalTok{)[}\KeywordTok{is.na}\NormalTok{(d_}\DecValTok{93}\NormalTok{)]}
\NormalTok{d_}\DecValTok{97}\NormalTok{[}\KeywordTok{is.na}\NormalTok{(d_}\DecValTok{97}\NormalTok{)]<-}\KeywordTok{imp.norm}\NormalTok{(prelim_}\DecValTok{97}\NormalTok{, thetaHat_}\DecValTok{97}\NormalTok{, d_}\DecValTok{97}\NormalTok{)[}\KeywordTok{is.na}\NormalTok{(d_}\DecValTok{97}\NormalTok{)]}
\KeywordTok{summary}\NormalTok{(d_}\DecValTok{97}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        X               year         latitude       longitude     
##  Min.   :  1.00   Min.   :1997   Min.   :-5.00   Min.   :-110.0  
##  1st Qu.: 92.75   1st Qu.:1997   1st Qu.:-2.75   1st Qu.:-110.0  
##  Median :184.50   Median :1997   Median :-1.00   Median :-102.5  
##  Mean   :184.50   Mean   :1997   Mean   :-1.75   Mean   :-102.5  
##  3rd Qu.:276.25   3rd Qu.:1997   3rd Qu.: 0.00   3rd Qu.: -95.0  
##  Max.   :368.00   Max.   :1997   Max.   : 0.00   Max.   : -95.0  
##  sea.surface.temp    air.temp        humidity         uwind       
##  Min.   :26.48    Min.   :25.20   Min.   :71.60   Min.   :-8.100  
##  1st Qu.:27.63    1st Qu.:26.86   1st Qu.:79.08   1st Qu.:-5.100  
##  Median :28.21    Median :27.27   Median :82.50   Median :-3.800  
##  Mean   :28.17    Mean   :27.28   Mean   :82.63   Mean   :-3.603  
##  3rd Qu.:28.66    3rd Qu.:27.68   3rd Qu.:86.50   3rd Qu.:-2.300  
##  Max.   :30.17    Max.   :29.85   Max.   :94.80   Max.   : 4.300  
##      vwind       
##  Min.   :-6.200  
##  1st Qu.: 1.375  
##  Median : 3.500  
##  Mean   : 2.775  
##  3rd Qu.: 4.600  
##  Max.   : 7.300
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(d_}\DecValTok{93}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        X              year         latitude    longitude     
##  Min.   :369.0   Min.   :1993   Min.   :-2   Min.   :-110.0  
##  1st Qu.:460.8   1st Qu.:1993   1st Qu.:-2   1st Qu.:-110.0  
##  Median :552.5   Median :1993   Median :-1   Median :-102.5  
##  Mean   :552.5   Mean   :1993   Mean   :-1   Mean   :-102.5  
##  3rd Qu.:644.2   3rd Qu.:1993   3rd Qu.: 0   3rd Qu.: -95.0  
##  Max.   :736.0   Max.   :1993   Max.   : 0   Max.   : -95.0  
##  sea.surface.temp    air.temp        humidity          uwind       
##  Min.   :21.60    Min.   :21.42   Min.   : 79.80   Min.   :-7.800  
##  1st Qu.:22.85    1st Qu.:22.75   1st Qu.: 85.80   1st Qu.:-5.100  
##  Median :23.51    Median :23.38   Median : 88.50   Median :-3.900  
##  Mean   :23.55    Mean   :23.37   Mean   : 90.46   Mean   :-3.829  
##  3rd Qu.:24.07    3rd Qu.:23.90   3rd Qu.: 92.17   3rd Qu.:-2.700  
##  Max.   :26.38    Max.   :25.03   Max.   :108.09   Max.   : 3.300  
##      vwind       
##  Min.   :-4.300  
##  1st Qu.: 1.600  
##  Median : 2.600  
##  Mean   : 2.496  
##  3rd Qu.: 3.500  
##  Max.   : 6.300
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(d_}\DecValTok{97}\OperatorTok{$}\NormalTok{humidity,d_}\DecValTok{97}\OperatorTok{$}\NormalTok{air.temp, }\DataTypeTok{col=}\StringTok{"red"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(d_}\DecValTok{93}\OperatorTok{$}\NormalTok{humidity,d_}\DecValTok{93}\OperatorTok{$}\NormalTok{air.temp, }\DataTypeTok{col=}\StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework_2_files/figure-latex/unnamed-chunk-9-2.pdf}


\end{document}
